<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Noks.Application</RootNamespace>
    <AssemblyName>Noks.Application</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Noks.Cryptography/Noks.Cryptography.csproj" />
    <ProjectReference Include="../Noks.Dct3/Noks.Dct3.csproj" />
    <ProjectReference Include="../Noks.Waku/Noks.Waku.csproj" />
  </ItemGroup>

</Project>
