namespace Noks.Cli;

public static class Mad2RegNames
{
    public static string Describe(uint offset)
    {
        return offset switch
        {
            0x00 => "CTSI asic version",
            0x01 => "CTSI mcu reset ctl",
            0x02 => "CTSI dsp reset ctl",
            0x03 => "CTSI watchdog",
            0x04 => "CTSI sleep counter msb",
            0x05 => "CTSI sleep counter lsb",
            0x06 => "CTSI sleep dest lsb",
            0x07 => "CTSI sleep dest msb",
            0x08 => "CTSI fiq active",
            0x09 => "CTSI irq active",
            0x0A => "CTSI fiq mask",
            0x0B => "CTSI irq mask",
            0x0C => "CTSI int control",
            0x0D => "CTSI clock control",
            0x0E => "CTSI int trigger",
            0x0F => "CTSI timer0 divider",
            0x10 => "CTSI timer0 counter msb",
            0x11 => "CTSI timer0 counter lsb",
            0x12 => "CTSI timer0 dest msb",
            0x13 => "CTSI timer0 dest lsb",
            0x15 => "PUP control",
            0x16 => "PUP fiq8 timer ctl",
            0x18 => "PUP mbus control",
            0x19 => "PUP mbus status",
            0x1A => "PUP mbus data",
            0x1B => "PUP vibrator",
            0x1C => "PUP buzzer divider",
            0x1E => "PUP buzzer volume",
            0x20 => "PUP genio lines",
            0x24 => "PUP genio direction",
            0x28 => "UIF kb row",
            0x29 => "UIF kb row 2",
            0x2A => "UIF kb col",
            0x2B => "UIF kb col 2",
            0x2C => "UIF ccont write",
            0x2D => "UIF gensio start",
            0x2E => "UIF lcd data",
            0x32 => "UIF ctrl io 2",
            0x33 => "UIF ctrl io 3",
            0x36 => "SIMI uart txd",
            0x37 => "SIMI uart rxd",
            0x38 => "SIMI uart int id",
            0x39 => "SIMI control",
            0x3A => "SIMI clock ctl",
            0x3C => "SIMI rxd fill",
            0x3F => "SIMI txd fill",
            0x68 => "UIF kb row p2",
            0x69 => "UIF kb row int",
            0x6A => "UIF kb col p2",
            0x6B => "UIF kb col int mask",
            0x6C => "UIF ccont read",
            0x6D => "UIF gensio status",
            0x6E => "UIF lcd command",
            0x6F => "UIF gensio sel1",
            >= 0x70 and <= 0x73 => $"UIF ctrl io {offset - 0x70} dir1",
            0xA8 => "UIF kb row dir",
            0xA9 => "UIF kb row p3",
            0xAA => "UIF kb col dir",
            0xAB => "UIF kb col p3",
            >= 0xAD and <= 0xAF => "UIF gensio sel2",
            >= 0xB0 and <= 0xB3 => $"UIF ctrl io {offset - 0xB0} dir2",
            >= 0xED and <= 0xEF => "UIF gensio sel3",
            >= 0xF0 and <= 0xF3 => $"UIF ctrl io {offset - 0xF0} input",
            _ => "unknown",
        };
    }
}
