#:package Avalonia@12.0.5

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Xml.Linq;
using Avalonia;
using Avalonia.Media;

if (args.Length != 2)
{
    Console.Error.WriteLine(
        "Usage: dotnet run tools/generate-phone-shell-data.cs -- <input.svg> <output.cs>");
    return 2;
}

string inputPath = Path.GetFullPath(args[0]);
string outputPath = Path.GetFullPath(args[1]);
XDocument document = XDocument.Load(inputPath, LoadOptions.PreserveWhitespace);
XElement root = document.Root ?? throw new InvalidDataException("The SVG has no root element.");
XNamespace svg = root.Name.Namespace;
XNamespace xlink = "http://www.w3.org/1999/xlink";

if (root.Attribute("width")?.Value != "402" || root.Attribute("height")?.Value != "958")
{
    throw new InvalidDataException("The phone SVG must use the 402 by 958 coordinate space.");
}

XElement RootElementWithId(string id)
    => root.Descendants().Single(element => element.Attribute("id")?.Value == id);

string PathData(XElement element)
    => element.Attribute("d")?.Value
        ?? throw new InvalidDataException($"The {element.Name.LocalName} element has no path data.");

XElement bodyPath = RootElementWithId("a");
XElement keypadCapPath = RootElementWithId("p");
XElement drawingGroup = root.Elements(svg + "g").Single();
List<XElement> shellPaths = drawingGroup.Elements(svg + "path").ToList();
XElement wordmark = RootElementWithId("nokia-wordmark");
List<XElement> wordmarkPaths = wordmark.Elements(svg + "path").ToList();

if (shellPaths.Count != 9 || wordmarkPaths.Count != 6)
{
    throw new InvalidDataException(
        $"The expected shell layout changed: {shellPaths.Count} shell paths and {wordmarkPaths.Count} wordmark paths.");
}

if (PathData(shellPaths[2]) != PathData(shellPaths[3]))
{
    throw new InvalidDataException("The two outer-shell light layers no longer share one path.");
}

XElement bodyUse = drawingGroup.Elements(svg + "use").First();
if (bodyUse.Attribute(xlink + "href")?.Value != "#a")
{
    throw new InvalidDataException("The drawing no longer starts with the expected phone-body path.");
}

string sourceHash = Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(inputPath)));
(string Name, string Data)[] paths =
[
    ("PhoneBody", PathData(bodyPath)),
    ("OuterShellHighlight", PathData(shellPaths[0])),
    ("OuterShellDark", PathData(shellPaths[1])),
    ("OuterShellLight", PathData(shellPaths[2])),
    ("UpperShellShade", PathData(shellPaths[4])),
    ("UpperShellBase", PathData(shellPaths[5])),
    ("UpperShellFace", PathData(shellPaths[6])),
    ("KeypadBed", PathData(shellPaths[7])),
    ("KeypadCap", PathData(keypadCapPath)),
    ("NokiaN", PathData(wordmarkPaths[0])),
    ("NokiaO", PathData(wordmarkPaths[1])),
    ("NokiaKStem", PathData(wordmarkPaths[2])),
    ("NokiaKArm", PathData(wordmarkPaths[3])),
    ("NokiaI", PathData(wordmarkPaths[4])),
    ("NokiaA", PathData(wordmarkPaths[5])),
    ("SpeakerHousing", PathData(shellPaths[8])),
];

StringBuilder output = new();
output.AppendLine("// <auto-generated />");
output.AppendLine("// Generated by tools/generate-phone-shell-data.cs from Assets/3310.svg.");
output.AppendLine();
output.AppendLine("using Avalonia;");
output.AppendLine("using Avalonia.Media;");
output.AppendLine();
output.AppendLine("namespace Noks.AvaloniaApp.Controls;");
output.AppendLine();
output.AppendLine("internal static class PhoneShellData");
output.AppendLine("{");
output.AppendLine($"    internal const string SourceSha256 = \"{sourceHash}\";");

foreach ((string name, string data) in paths)
{
    AppendGeometryFactory(output, name, data);
}

output.AppendLine("}");
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, output.ToString().ReplaceLineEndings("\n"), new UTF8Encoding(false));
Console.WriteLine($"Generated {outputPath} from SHA-256 {sourceHash}.");
return 0;

static void AppendGeometryFactory(StringBuilder output, string name, string pathData)
{
    PathGeometry source = PathGeometry.Parse(pathData);
    output.AppendLine();
    output.AppendLine($"    internal static StreamGeometry Create{name}()");
    output.AppendLine("    {");
    output.AppendLine("        StreamGeometry geometry = new();");
    output.AppendLine("        using (StreamGeometryContext context = geometry.Open())");
    output.AppendLine("        {");
    output.AppendLine($"            context.SetFillRule(FillRule.{source.FillRule});");

    foreach (PathFigure figure in source.Figures ?? [])
    {
        output.AppendLine($"            context.BeginFigure({PointSource(figure.StartPoint)}, {Bool(figure.IsFilled)});");
        foreach (PathSegment segment in figure.Segments ?? [])
        {
            AppendSegment(output, segment);
        }

        output.AppendLine($"            context.EndFigure({Bool(figure.IsClosed)});");
    }

    output.AppendLine("        }");
    output.AppendLine();
    output.AppendLine("        return geometry;");
    output.AppendLine("    }");
}

static void AppendSegment(StringBuilder output, PathSegment segment)
{
    switch (segment)
    {
        case LineSegment line:
            output.AppendLine($"            context.LineTo({PointSource(line.Point)});");
            break;
        case BezierSegment bezier:
            output.AppendLine(
                $"            context.CubicBezierTo({PointSource(bezier.Point1)}, {PointSource(bezier.Point2)}, {PointSource(bezier.Point3)});");
            break;
        case QuadraticBezierSegment quadratic:
            output.AppendLine(
                $"            context.QuadraticBezierTo({PointSource(quadratic.Point1)}, {PointSource(quadratic.Point2)});");
            break;
        case ArcSegment arc:
            output.AppendLine(
                $"            context.ArcTo({PointSource(arc.Point)}, {SizeSource(arc.Size)}, {Number(arc.RotationAngle)}, " +
                $"{Bool(arc.IsLargeArc)}, SweepDirection.{arc.SweepDirection});");
            break;
        case PolyLineSegment polyLine:
            foreach (Point point in polyLine.Points ?? [])
            {
                output.AppendLine($"            context.LineTo({PointSource(point)});");
            }

            break;
        case PolyBezierSegment polyBezier:
            IReadOnlyList<Point> points = polyBezier.Points ?? [];
            if (points.Count % 3 != 0)
            {
                throw new InvalidDataException("A poly-Bezier segment does not contain complete point triplets.");
            }

            for (int index = 0; index < points.Count; index += 3)
            {
                output.AppendLine(
                    $"            context.CubicBezierTo({PointSource(points[index])}, {PointSource(points[index + 1])}, " +
                    $"{PointSource(points[index + 2])});");
            }

            break;
        default:
            throw new InvalidDataException($"Unsupported Avalonia path segment: {segment.GetType().Name}.");
    }
}

static string PointSource(Point point) => $"new Point({Number(point.X)}, {Number(point.Y)})";

static string SizeSource(Size size) => $"new Size({Number(size.Width)}, {Number(size.Height)})";

static string Number(double value)
{
    double rounded = Math.Round(value, 6, MidpointRounding.AwayFromZero);
    if (rounded == 0)
    {
        rounded = 0;
    }

    return rounded.ToString("0.######", CultureInfo.InvariantCulture);
}

static string Bool(bool value) => value ? "true" : "false";
