// <auto-generated />
// Generated by tools/generate-phone-shell-data.cs from Assets/3310.svg.

using Avalonia;
using Avalonia.Media;

namespace Noks.AvaloniaApp.Controls;

internal static class PhoneShellData
{
    internal const string SourceSha256 = "468523d7ba09eb34de86bd152e5c4448d30f2bf5a465ff3a4fa59fbf90edf83c";

    internal static StreamGeometry CreatePhoneBody()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(201.707, 0), true);
            context.CubicBezierTo(new Point(152.623, 0.054), new Point(71.519, 13.472), new Point(71.519, 13.472));
            context.CubicBezierTo(new Point(47.473, 16.998), new Point(25.081, 39.482), new Point(21.479, 63.512));
            context.CubicBezierTo(new Point(21.479, 63.512), new Point(11.616, 121.535), new Point(5.801, 201.246));
            context.CubicBezierTo(new Point(0.108, 279.277), new Point(1, 378.51), new Point(1, 452.852));
            context.CubicBezierTo(new Point(1, 599.232), new Point(27.97, 892.23), new Point(27.97, 892.23));
            context.CubicBezierTo(new Point(30.822, 925.241), new Point(60.038, 953.13), new Point(93.14, 954.526));
            context.CubicBezierTo(new Point(93.14, 954.526), new Point(167.504, 957.951), new Point(201, 957.999));
            context.LineTo(new Point(201.707, 958));
            context.CubicBezierTo(new Point(235.203, 957.951), new Point(309.567, 954.526), new Point(309.567, 954.526));
            context.CubicBezierTo(new Point(342.669, 953.131), new Point(371.885, 925.241), new Point(374.737, 892.23));
            context.CubicBezierTo(new Point(374.737, 892.23), new Point(401.707, 599.232), new Point(401.707, 452.852));
            context.CubicBezierTo(new Point(401.707, 378.51), new Point(402.599, 279.277), new Point(396.907, 201.246));
            context.CubicBezierTo(new Point(391.091, 121.536), new Point(381.227, 63.513), new Point(381.227, 63.513));
            context.CubicBezierTo(new Point(377.627, 39.481), new Point(355.241, 16.976), new Point(331.202, 13.427));
            context.CubicBezierTo(new Point(331.202, 13.427), new Point(251.08, 0.053), new Point(202, 0));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateOuterShellHighlight()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(201.197, -3.469), true);
            context.CubicBezierTo(new Point(274.101, -3.399), new Point(324.549, 7.626), new Point(324.549, 7.626));
            context.CubicBezierTo(new Point(341.442, 10.446), new Point(357.733, 26.6), new Point(360.997, 43.4));
            context.CubicBezierTo(new Point(360.997, 43.4), new Point(373.719, 104.22), new Point(384.736, 190.92));
            context.CubicBezierTo(new Point(390.266, 267.96), new Point(389.399, 365.932), new Point(389.399, 439.329));
            context.CubicBezierTo(new Point(389.399, 583.849), new Point(360.984, 899.266), new Point(360.984, 899.266));
            context.CubicBezierTo(new Point(359.414, 917.416), new Point(343.527, 934.424), new Point(325.53, 937.246));
            context.CubicBezierTo(new Point(325.53, 937.246), new Point(311.856, 940.026), new Point(279.862, 942.886));
            context.CubicBezierTo(new Point(247.869, 945.746), new Point(218.526, 945.746), new Point(201.502, 945.746));
            context.LineTo(new Point(201.502, 945.466));
            context.CubicBezierTo(new Point(183.796, 945.494), new Point(145.656, 946.527), new Point(117.605, 944.199));
            context.CubicBezierTo(new Point(89.175, 941.839), new Point(76.938, 938.352), new Point(76.938, 938.352));
            context.CubicBezierTo(new Point(59.068, 934.764), new Point(43.283, 917.135), new Point(41.714, 898.985));
            context.CubicBezierTo(new Point(41.714, 898.985), new Point(13.299, 583.569), new Point(13.299, 439.048));
            context.CubicBezierTo(new Point(13.299, 365.651), new Point(12.432, 267.678), new Point(17.962, 190.638));
            context.CubicBezierTo(new Point(28.979, 103.938), new Point(41.702, 43.119), new Point(41.702, 43.119));
            context.CubicBezierTo(new Point(44.965, 26.319), new Point(61.252, 10.139), new Point(78.14, 7.294));
            context.CubicBezierTo(new Point(78.14, 7.294), new Point(127.912, -3.75), new Point(201.196, -3.75));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateOuterShellDark()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(198.2, 5.16), true);
            context.CubicBezierTo(new Point(269.764, 5.23), new Point(318.742, 15.967), new Point(318.742, 15.967));
            context.CubicBezierTo(new Point(335.622, 18.779), new Point(351.912, 34.931), new Point(355.174, 51.731));
            context.CubicBezierTo(new Point(355.174, 51.731), new Point(367.559, 110.891), new Point(378.374, 196.013));
            context.CubicBezierTo(new Point(383.802, 271.653), new Point(382.952, 367.843), new Point(382.952, 439.905));
            context.CubicBezierTo(new Point(382.952, 581.797), new Point(355.109, 890.875), new Point(355.109, 890.875));
            context.CubicBezierTo(new Point(353.539, 909.032), new Point(337.651, 926.035), new Point(319.652, 928.853));
            context.CubicBezierTo(new Point(319.652, 928.853), new Point(306.83, 931.495), new Point(275.422, 934.303));
            context.CubicBezierTo(new Point(244.016, 937.111), new Point(215.211, 937.111), new Point(198.499, 937.111));
            context.LineTo(new Point(198.499, 936.836));
            context.CubicBezierTo(new Point(181.118, 936.863), new Point(143.677, 937.878), new Point(116.14, 935.592));
            context.CubicBezierTo(new Point(88.232, 933.276), new Point(76.802, 929.957), new Point(76.802, 929.957));
            context.CubicBezierTo(new Point(58.938, 926.377), new Point(43.158, 908.756), new Point(41.589, 890.6));
            context.CubicBezierTo(new Point(41.589, 890.6), new Point(13.746, 581.521), new Point(13.746, 439.629));
            context.CubicBezierTo(new Point(13.746, 367.567), new Point(12.896, 271.376), new Point(18.324, 195.738));
            context.CubicBezierTo(new Point(29.139, 110.615), new Point(41.524, 51.455), new Point(41.524, 51.455));
            context.CubicBezierTo(new Point(44.786, 34.655), new Point(61.071, 18.476), new Point(77.944, 15.641));
            context.CubicBezierTo(new Point(77.944, 15.641), new Point(126.258, 4.885), new Point(198.199, 4.885));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateOuterShellLight()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(201.201, 10.588), true);
            context.CubicBezierTo(new Point(271.93, 10.655), new Point(319.971, 21.209), new Point(319.971, 21.209));
            context.CubicBezierTo(new Point(336.873, 24.02), new Point(353.154, 40.172), new Point(356.415, 56.976));
            context.CubicBezierTo(new Point(356.415, 56.976), new Point(368.588, 115.086), new Point(379.276, 199.216));
            context.CubicBezierTo(new Point(384.642, 273.974), new Point(383.801, 369.044), new Point(383.801, 440.266));
            context.CubicBezierTo(new Point(383.801, 580.506), new Point(356.315, 885.606), new Point(356.315, 885.606));
            context.CubicBezierTo(new Point(354.746, 903.762), new Point(338.855, 920.758), new Point(320.852, 923.576));
            context.CubicBezierTo(new Point(320.852, 923.576), new Point(308.566, 926.13), new Point(277.525, 928.906));
            context.CubicBezierTo(new Point(246.484, 931.681), new Point(218.015, 931.681), new Point(201.497, 931.681));
            context.LineTo(new Point(201.497, 931.409));
            context.CubicBezierTo(new Point(184.318, 931.437), new Point(147.314, 932.439), new Point(120.098, 930.18));
            context.CubicBezierTo(new Point(92.515, 927.89), new Point(81.596, 924.68), new Point(81.596, 924.68));
            context.CubicBezierTo(new Point(63.731, 921.102), new Point(47.951, 903.49), new Point(46.383, 885.334));
            context.CubicBezierTo(new Point(46.383, 885.334), new Point(18.897, 580.234), new Point(18.897, 439.994));
            context.CubicBezierTo(new Point(18.897, 368.772), new Point(18.057, 273.702), new Point(23.422, 198.944));
            context.CubicBezierTo(new Point(34.11, 114.814), new Point(46.283, 56.704), new Point(46.283, 56.704));
            context.CubicBezierTo(new Point(49.544, 39.899), new Point(65.819, 23.722), new Point(82.715, 20.887));
            context.CubicBezierTo(new Point(82.715, 20.887), new Point(130.098, 10.315), new Point(201.201, 10.315));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateUpperShellShade()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(319.759, 13.716), true);
            context.CubicBezierTo(new Point(336.915, 16.569), new Point(353.441, 32.963), new Point(356.751, 50.02));
            context.CubicBezierTo(new Point(356.751, 50.02), new Point(369.107, 109.003), new Point(379.956, 194.399));
            context.CubicBezierTo(new Point(385.402, 270.28), new Point(384.549, 298.772), new Point(384.549, 371.065));
            context.CubicBezierTo(new Point(384.549, 491.82), new Point(349.777, 631.657), new Point(199.204, 631.657));
            context.CubicBezierTo(new Point(65.27, 631.657), new Point(14.16, 508), new Point(14.16, 370.79));
            context.CubicBezierTo(new Point(14.16, 298.5), new Point(13.306, 270.005), new Point(18.752, 194.123));
            context.CubicBezierTo(new Point(29.602, 108.728), new Point(41.958, 49.744), new Point(41.958, 49.744));
            context.CubicBezierTo(new Point(45.268, 32.688), new Point(61.788, 16.267), new Point(78.937, 13.39));
            context.CubicBezierTo(new Point(78.937, 13.39), new Point(127.032, 2.658), new Point(199.204, 2.658));
            context.CubicBezierTo(new Point(270.996, 3.004), new Point(319.759, 13.717), new Point(319.759, 13.717));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateUpperShellBase()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(317.97, 17.21), true);
            context.CubicBezierTo(new Point(334.873, 20.02), new Point(351.154, 36.172), new Point(354.415, 52.976));
            context.CubicBezierTo(new Point(354.415, 52.976), new Point(366.588, 111.086), new Point(377.276, 195.216));
            context.CubicBezierTo(new Point(382.642, 269.974), new Point(381.801, 298.044), new Point(381.801, 369.266));
            context.CubicBezierTo(new Point(381.801, 508), new Point(331.151, 626), new Point(199.201, 626));
            context.CubicBezierTo(new Point(67.25, 626), new Point(21.42, 508), new Point(16.897, 368.994));
            context.CubicBezierTo(new Point(14.582, 297.884), new Point(16.057, 269.702), new Point(21.422, 194.944));
            context.CubicBezierTo(new Point(32.11, 110.814), new Point(44.283, 52.704), new Point(44.283, 52.704));
            context.CubicBezierTo(new Point(47.544, 35.899), new Point(63.819, 19.722), new Point(80.715, 16.887));
            context.CubicBezierTo(new Point(80.715, 16.887), new Point(128.098, 6.315), new Point(199.201, 6.315));
            context.CubicBezierTo(new Point(269.93, 6.655), new Point(317.971, 17.209), new Point(317.971, 17.209));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateUpperShellFace()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(199.764, 567.96), true);
            context.LineTo(new Point(200.684, 567.96));
            context.CubicBezierTo(new Point(339.222, 566.928), new Point(371.701, 449.925), new Point(371.701, 360.44));
            context.CubicBezierTo(new Point(371.701, 293.473), new Point(371.461, 267.236), new Point(366.609, 197.063));
            context.CubicBezierTo(new Point(356.943, 118.09), new Point(343.935, 60.543), new Point(343.935, 60.543));
            context.CubicBezierTo(new Point(337.337, 29.809), new Point(321.269, 24.585), new Point(305.99, 21.923));
            context.CubicBezierTo(new Point(305.99, 21.923), new Point(263.515, 12.086), new Point(199.684, 12.001));
            context.LineTo(new Point(198.844, 12));
            context.CubicBezierTo(new Point(135.014, 12.086), new Point(92.538, 21.924), new Point(92.538, 21.924));
            context.CubicBezierTo(new Point(77.259, 24.584), new Point(61.191, 29.809), new Point(54.593, 60.544));
            context.CubicBezierTo(new Point(54.593, 60.544), new Point(41.585, 118.09), new Point(31.919, 197.063));
            context.CubicBezierTo(new Point(27.067, 267.236), new Point(26.828, 293.473), new Point(26.828, 360.44));
            context.CubicBezierTo(new Point(26.828, 449.925), new Point(60.297, 566.928), new Point(198.844, 567.954));
            context.CubicBezierTo(new Point(199.151, 567.961), new Point(199.458, 567.96), new Point(199.764, 567.959));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKeypadBed()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(298.344, 520.05), true);
            context.CubicBezierTo(new Point(354.194, 475.748), new Point(360.858, 400.047), new Point(363.702, 338));
            context.CubicBezierTo(new Point(365.131, 270.667), new Point(366.468, 271.27), new Point(361.735, 200.538));
            context.CubicBezierTo(new Point(352.307, 120.936), new Point(341.568, 60.915), new Point(341.568, 60.915));
            context.CubicBezierTo(new Point(338.692, 45.016), new Point(330.115, 29.54), new Point(303.358, 24.004));
            context.CubicBezierTo(new Point(303.358, 24.004), new Point(261.935, 13.981), new Point(199.682, 13.891));
            context.CubicBezierTo(new Point(136.586, 13.981), new Point(95.163, 24.004), new Point(95.163, 24.004));
            context.CubicBezierTo(new Point(68.407, 29.54), new Point(59.829, 45.016), new Point(56.953, 60.915));
            context.CubicBezierTo(new Point(56.953, 60.915), new Point(46.214, 120.936), new Point(36.786, 200.538));
            context.CubicBezierTo(new Point(32.053, 271.27), new Point(33.39, 270.668), new Point(34.819, 338.001));
            context.CubicBezierTo(new Point(37.663, 400.041), new Point(44.326, 475.735), new Point(99.866, 520.038));
            context.CubicBezierTo(new Point(117.002, 515.308), new Point(156.168, 504.828), new Point(199.682, 504.828));
            context.CubicBezierTo(new Point(245.155, 504.828), new Point(265.198, 510.877), new Point(298.344, 520.049));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKeypadCap()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(262.149, 503.05), true);
            context.CubicBezierTo(new Point(317.325, 459.098), new Point(323.909, 383.995), new Point(326.719, 322.44));
            context.CubicBezierTo(new Point(328.129, 255.638), new Point(329.451, 256.236), new Point(324.775, 186.063));
            context.CubicBezierTo(new Point(315.46, 107.09), new Point(304.852, 47.543), new Point(304.852, 47.543));
            context.CubicBezierTo(new Point(302.01, 31.77), new Point(293.536, 16.416), new Point(267.102, 10.923));
            context.CubicBezierTo(new Point(267.102, 10.923), new Point(226.179, 0.981), new Point(164.677, 0.891));
            context.CubicBezierTo(new Point(102.343, 0.981), new Point(61.42, 10.924), new Point(61.42, 10.924));
            context.CubicBezierTo(new Point(34.986, 16.416), new Point(26.512, 31.77), new Point(23.67, 47.544));
            context.CubicBezierTo(new Point(23.67, 47.544), new Point(13.062, 107.09), new Point(3.747, 186.063));
            context.CubicBezierTo(new Point(-0.93, 256.236), new Point(0.392, 255.638), new Point(1.803, 322.44));
            context.CubicBezierTo(new Point(4.613, 383.99), new Point(11.195, 459.085), new Point(66.065, 503.038));
            context.CubicBezierTo(new Point(82.995, 498.346), new Point(121.688, 487.949), new Point(164.677, 487.949));
            context.CubicBezierTo(new Point(209.602, 487.949), new Point(229.402, 493.949), new Point(262.149, 503.049));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateNokiaN()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(7.989, 27.318), true);
            context.LineTo(new Point(0, 27.318));
            context.LineTo(new Point(0, 0.355));
            context.LineTo(new Point(13.869, 0.355));
            context.LineTo(new Point(30.152, 20.455));
            context.LineTo(new Point(30.289, 20.802));
            context.LineTo(new Point(30.289, 0.355));
            context.LineTo(new Point(38.277, 0.355));
            context.LineTo(new Point(38.277, 27.318));
            context.LineTo(new Point(24.492, 27.318));
            context.LineTo(new Point(8.092, 7.077));
            context.LineTo(new Point(7.989, 6.835));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateNokiaO()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(49.251, 19.328), true);
            context.CubicBezierTo(new Point(49.251, 20.505), new Point(49.838, 20.849), new Point(51.737, 20.849));
            context.LineTo(new Point(67.127, 20.849));
            context.CubicBezierTo(new Point(69.029, 20.849), new Point(69.752, 20.16), new Point(69.752, 19.328));
            context.LineTo(new Point(69.752, 8.333));
            context.CubicBezierTo(new Point(69.752, 7.021), new Point(69.133, 6.671), new Point(67.23, 6.671));
            context.LineTo(new Point(51.737, 6.671));
            context.CubicBezierTo(new Point(49.837, 6.671), new Point(49.251, 7.401), new Point(49.251, 8.333));
            context.EndFigure(true);
            context.BeginFigure(new Point(41.609, 7.158), true);
            context.CubicBezierTo(new Point(41.609, 5.118), new Point(41.954, 3.701), new Point(43.404, 2.388));
            context.CubicBezierTo(new Point(45.789, 0), new Point(48.627, 0), new Point(59.484, 0));
            context.CubicBezierTo(new Point(70.341, 0), new Point(73.074, 0), new Point(75.46, 2.388));
            context.CubicBezierTo(new Point(76.911, 3.701), new Point(77.259, 5.118), new Point(77.259, 7.158));
            context.LineTo(new Point(77.259, 20.402));
            context.CubicBezierTo(new Point(77.259, 22.406), new Point(76.911, 23.962), new Point(75.46, 25.277));
            context.CubicBezierTo(new Point(73.074, 27.522), new Point(70.24, 27.664), new Point(59.381, 27.664));
            context.CubicBezierTo(new Point(48.524, 27.664), new Point(45.79, 27.522), new Point(43.404, 25.277));
            context.CubicBezierTo(new Point(41.954, 23.962), new Point(41.609, 22.406), new Point(41.609, 20.402));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateNokiaKStem()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(89.117, 0.372), true);
            context.LineTo(new Point(89.117, 27.309));
            context.LineTo(new Point(80.646, 27.309));
            context.LineTo(new Point(80.646, 0.372));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateNokiaKArm()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(103.64, 0.372), true);
            context.LineTo(new Point(114.879, 0.372));
            context.LineTo(new Point(99.352, 13.479));
            context.LineTo(new Point(116.885, 27.309));
            context.LineTo(new Point(104.608, 27.309));
            context.LineTo(new Point(89.117, 13.479));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateNokiaI()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(126.911, 0.355), true);
            context.LineTo(new Point(126.911, 27.31));
            context.LineTo(new Point(118.439, 27.31));
            context.LineTo(new Point(118.439, 0.355));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateNokiaA()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(143.46, 16.831), true);
            context.LineTo(new Point(153.972, 16.831));
            context.LineTo(new Point(148.716, 7.047));
            context.EndFigure(true);
            context.BeginFigure(new Point(140.381, 22.676), true);
            context.LineTo(new Point(137.858, 27.309));
            context.LineTo(new Point(128.452, 27.309));
            context.LineTo(new Point(143.356, 0.372));
            context.LineTo(new Point(154.214, 0.372));
            context.LineTo(new Point(168.978, 27.309));
            context.LineTo(new Point(159.574, 27.309));
            context.LineTo(new Point(157.083, 22.676));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateSpeakerHousing()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(185, 102.654), true);
            context.CubicBezierTo(new Point(185, 78.061), new Point(191.705, 30.954), new Point(191.705, 30.954));
            context.CubicBezierTo(new Point(192.006, 28.77), new Point(194.043, 27), new Point(196.251, 27));
            context.LineTo(new Point(202.749, 27));
            context.CubicBezierTo(new Point(204.959, 27), new Point(206.997, 28.776), new Point(207.295, 30.954));
            context.CubicBezierTo(new Point(207.295, 30.954), new Point(214, 78.061), new Point(214, 102.654));
            context.CubicBezierTo(new Point(214, 124.812), new Point(207.35, 167.059), new Point(207.35, 167.059));
            context.CubicBezierTo(new Point(207.018, 169.235), new Point(204.957, 171), new Point(202.75, 171));
            context.LineTo(new Point(196.25, 171));
            context.CubicBezierTo(new Point(194.041, 171), new Point(191.979, 169.239), new Point(191.647, 167.038));
            context.CubicBezierTo(new Point(191.647, 167.038), new Point(185, 124.812), new Point(185, 102.654));
            context.EndFigure(false);
        }

        return geometry;
    }
}
